---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build: null
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run markdown lint
      run: |
        npm install remark-cli remark-preset-lint-consistent
        npx remark . --use remark-preset-lint-consistent --frail
